#!/usr/bin/env sh
# Copyright (C) 2010-2022 The ESPResSo project
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#

if test -n "$PYTHONPATH"; then
  PYTHONPATH="/home/mdi220/simulations/ALL_ESPRESSO/EspressoMD-4.2.1/ligand_receptor/src/python:$PYTHONPATH"
else
  PYTHONPATH="/home/mdi220/simulations/ALL_ESPRESSO/EspressoMD-4.2.1/ligand_receptor/src/python"
fi
export PYTHONPATH

# Open MPI 4.x cannot run in singleton mode on some NUMA systems
if [ "ON" = "ON" ] && [ "OFF" = "ON" ]; then
  if [ -z "${OMPI_COMM_WORLD_SIZE}" ] && [ "${OMPI_MCA_hwloc_base_binding_policy}" = "numa" ]; then
    if test -f /proc/cpuinfo && grep --quiet -P "^[Mm]odel name[ \t]*:[ \t]+AMD (EPYC|Ryzen)( |$)" /proc/cpuinfo; then
      echo "warning: if Open MPI fails to set processor affinity, set environment variable OMPI_MCA_hwloc_base_binding_policy to \"none\" or \"l3cache\""
    fi
  fi
fi

if [ "GNU" != "GNU" ] && [ "OFF" = "ON" ]; then
  asan_lib=$("/usr/bin/g++-10" /dev/null -### -o /dev/null -fsanitize=address 2>&1 | grep -o '[" ][^" ]*libclang_rt.asan[^" ]*[^s][" ]' | sed 's/[" ]//g' | sed 's/\.a$/.so/g')
  export DYLD_INSERT_LIBRARIES="$asan_lib"
  for lib in $asan_lib; do
      test -f $lib && LD_PRELOAD="$lib $LD_PRELOAD"
  done
fi
if [ "GNU" != "GNU" ] && [ "OFF" = "ON" ] && [ "OFF" != "ON" ]; then
  ubsan_lib=$("/usr/bin/g++-10" /dev/null -### -o /dev/null -fsanitize=undefined 2>&1 | grep -o '[" ][^" ]*libclang_rt.ubsan[^" ]*[^s][" ]' | sed 's/[" ]//g' | sed 's/\.a$/.so/g')
  for lib in $ubsan_lib; do
    test -f $lib && LD_PRELOAD="$lib $LD_PRELOAD"
  done
fi
export LD_PRELOAD
if [ "OFF" = "ON" ]; then
  export UBSAN_OPTIONS="print_stacktrace=1 suppressions=\"/home/mdi220/simulations/ALL_ESPRESSO/EspressoMD-4.2.1/maintainer/CI/ubsan.supp\" $UBSAN_OPTIONS"
  if [ "OFF" = "ON" ]; then
    export UBSAN_OPTIONS="halt_on_error=1 $UBSAN_OPTIONS"
  fi
fi
if [ "OFF" = "ON" ]; then
  ASAN_OPTIONS="protect_shadow_gap=0 allocator_may_return_null=1 $ASAN_OPTIONS"
  if [ "OFF" = "ON" ]; then
    ASAN_OPTIONS="halt_on_error=1 $ASAN_OPTIONS"
  fi
  if [ "$1" = "--leaks" ]; then
    shift
  else
    ASAN_OPTIONS="$ASAN_OPTIONS detect_leaks=0"
  fi
  export ASAN_OPTIONS
fi
if [ "" = "ON" ] && [ "OFF" = "ON" ]; then
  export MSAN_OPTIONS="halt_on_error=1 $MSAN_OPTIONS"
fi

case "$1" in
    --gdb)
        shift
        [ "/home/mdi220/.virtualenvs/esp/bin/python3.8" = "IPYTHON_EXECUTABLE-NOTFOUND" ] && exec gdb -ex "set print thread-events off" -ex "set exec-wrapper sh -c 'exec \"IPYTHON_EXECUTABLE-NOTFOUND\" \"\$@\"'" --args "/home/mdi220/.virtualenvs/esp/bin/python3.8" "$@"
        exec gdb --args "/home/mdi220/.virtualenvs/esp/bin/python3.8" "$@"
        ;;
    --lldb)
        shift
        exec lldb -- "/home/mdi220/.virtualenvs/esp/bin/python3.8" "$@"
        ;;
    --coverage)
        shift
        exec /home/mdi220/.virtualenvs/esp/bin/python3.8 -m coverage run --source=/home/mdi220/simulations/ALL_ESPRESSO/EspressoMD-4.2.1/ligand_receptor/testsuite/ --rcfile="/home/mdi220/simulations/ALL_ESPRESSO/EspressoMD-4.2.1/.coveragerc" "$@"
        ;;
    --valgrind)
        shift
        exec valgrind --leak-check=full "/home/mdi220/.virtualenvs/esp/bin/python3.8" "$@"
        ;;
    --cuda-gdb)
        shift
        exec cuda-gdb --args "/home/mdi220/.virtualenvs/esp/bin/python3.8" "$@"
        ;;
    --cuda-memcheck)
        shift
        exec cuda-memcheck "/home/mdi220/.virtualenvs/esp/bin/python3.8" "$@"
        ;;
    --gdb=*)
        options="${1#*=}"
        shift
        [ "/home/mdi220/.virtualenvs/esp/bin/python3.8" = "IPYTHON_EXECUTABLE-NOTFOUND" ] && exec gdb -ex "set print thread-events off" -ex "set exec-wrapper sh -c 'exec \"IPYTHON_EXECUTABLE-NOTFOUND\" \"\$@\"'" ${options} --args "/home/mdi220/.virtualenvs/esp/bin/python3.8" "$@"
        exec gdb ${options} --args "/home/mdi220/.virtualenvs/esp/bin/python3.8" "$@"
        ;;
    --lldb=*)
        options="${1#*=}"
        shift
        exec lldb ${options} -- "/home/mdi220/.virtualenvs/esp/bin/python3.8" "$@"
        ;;
    --valgrind=*)
        options="${1#*=}"
        shift
        exec valgrind ${options} "/home/mdi220/.virtualenvs/esp/bin/python3.8" "$@"
        ;;
    --cuda-gdb=*)
        options="${1#*=}"
        shift
        exec cuda-gdb ${options} --args "/home/mdi220/.virtualenvs/esp/bin/python3.8" "$@"
        ;;
    --cuda-memcheck=*)
        options="${1#*=}"
        shift
        exec cuda-memcheck ${options} "/home/mdi220/.virtualenvs/esp/bin/python3.8" "$@"
        ;;
    *)
        exec "/home/mdi220/.virtualenvs/esp/bin/python3.8" "$@"
        ;;
esac
